### ISSUE TITLE
non-matching extents...is this ok?

### ISSUE THREAD

**Issue by nagyrc** [nagyrc/C_fire_invasives#2]
https://github.com/nagyrc/C_fire_invasives/blob/59d2212953481cac6957b955e151f42d454337ae/4_add_fire_data.R#L171-L174

**Comment by mbjoseph** [comment]
It is fine - the extents do not need to be identical for `raster::extract` to work. The main thing to check would be that the extent of `studyid_sf` is bounded by the extent of the MODIS data.
